services:
    auto_form_field.listener_extension:
        class: AppVentus\AutoFormFillBundle\Form\Extension\ListenerExtension
        arguments: ["@doctrine.orm.entity_manager", "@auto_form_field.filler", "@request", %av_auto_form_fill.enabled%]
        scope: request
        tags:
            - { name: form.type_extension, alias: form }
    auto_form_field.filler:
        class: AppVentus\AutoFormFillBundle\Service\Filler
        arguments: ["@doctrine.orm.entity_manager"]
